image: node:latest

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm run build
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
