apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: szuflada
build:
  local:
    useBuildkit: true
  artifacts:
    - image: harbor.k8s.lan/sprawunki/szuflada
      docker:
        dockerfile: Dockerfile
        target: app
      context: '.'
manifests:
  kustomize:
    paths:
      - deploy/base
profiles:
  - name: development
    activation:
      - command: dev
    build:
      artifacts:
        - image: harbor.k8s.lan/sprawunki/szuflada
          docker:
            dockerfile: Dockerfile
            target: dev
          context: '.'
          sync:
            manual:
              - src: 'src/**'
                dest: '/app'
    manifests:
      kustomize:
        paths:
          - deploy/overlays/dev
portForward:
  - resourceType: service
    resourceName: szuflada
    port:  80
    localPort: 5173
